# name: CI/CD Pipeline

# on:
#   push:
#     branches: ["main"]

#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     name: Build, Test, Deploy
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Build docker image
#         run: docker build . -t caju:latest

#       - name: Run tests
#         run: docker run caju:latest yarn jest

#       - name: Run linter
#         run: docker run caju:latest yarn lint

#       - name: Build frontend
#         run: docker run caju:latest yarn build

#       - name: Deploy frontend
#         run: docker run -d -p 3001:3001 caju:latest yarn preview

#       - name: Deploy backend
#         run: docker run -d -p 3000:3000 caju:latest yarn db:init
